---
- name: ping linux nodes
  hosts: routers
  tasks:
  - name: ping all linux nodes
    ansible.builtin.ping

- name: ping windows nodes
  hosts: windows
  gather_facts: false
  become: false
  tasks:
  - name: ping all windows nodes
    ansible.windows.win_ping

- name: ping exos nodes
  hosts: exos
  gather_facts: false
  tasks:
  - name: ping all exos switch except main
    ansible.builtin.ping
