---
- name: Get VLAN information from EXOS switches
  hosts: exos_switches
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: exos
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
  tasks:
    - name: Retrieve VLAN configuration
      cli_command:
        command: "show vlan"
      register: vlan_output

    - name: Display VLAN information
      debug:
        msg:
          - "VLANs on {{ inventory_hostname }}:"
          - "{{ vlan_output.stdout_lines }}"