---
- name: Create VLANs on EXOS Layer 3 switches
  hosts: exos_switches
  gather_facts: no
  connection: network_cli
  vars:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    ansible_network_os: exos
  tasks:
    - name: Create VLANS
      ansible.network.eos_vlan:
        name: "{{Hostname}}"
        vlan_id: "{{Vlan}}"
        state: present
      register: "vlan_creation"