---
- name: Create VLANs on EXOS Layer 3 switches
  hosts: exos_switches
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    ansible_network_os: exos
  tasks:
    -name: create Vlans
      cli_command:
        command: "create vlan {{ vlan_name }} id {{ vlan_id }}"
    vars"
      vlan_name: "{{ hostname }}"
      vlan_id: "{{ vlan }}"
   # - name: Create VLANS
   #   ansible.network.eos_vlan:
   #     name: "{{hostname}}"
   #     vlan_id: "{{vlan}}"
   #     state: present
   #   register: "vlan_creation"
    
    - name: Show information
      debug:
        msg:
          - "Username: {{ new_username }}"
          - "Password: {{ new_password }}"
  