---
-name: vlans
 hosts: switches

vars_files: 
    -vars.yml

 tasks:
  - name: check vlans
    exos_command:
      commands: show version

  - name: set vlans
    exos_command:
      commands: show version