---
- name: Create new accounts on EXOS switches
  hosts: exos_switches
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: exos
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
  tasks:
    - name: Create a new user account
      cli_command:
        command: "create account admin {{ new_username }} {{ new_password }}"

