---
- name: Create Windows User Accounts
  hosts: windows
  gather_facts: no
  tasks:
    - name: Create a new user account
      win_user:
        name: "{{Username}}"          
        password: "{{password}}"  
        state: present  
        groups:
          - "Users" 
          - "Administrators"  
        comment: "Test User Account"  
        update_password: always
