---
- name: Create Windows User Accounts
  hosts: windows
  gather_facts: no
  become: false
  vars:
    ansible_user: Administrator
    ansible_password: P@ssw0rd
    ansible_connection: winrm
    
  tasks:
    - name: Create a new user account
      win_user:
        name: "{{ username }}"          
        password: "{{ password }}"  
        state: present  
        groups:
          - "Users" 
          - "Administrators"  
        password_never_expires: yes  
        update_password: always

    - name: Debug user details
      debug:
        msg:
          - "Username: {{ username }}"
          - "Password: {{ password }}"


